### ISSUE TITLE
Compiler error "Wrong number of args (0) passed to: generate/generate-query-fn/query-wrapper-fn--1881"

### ISSUE THREAD

**Issue by mveytsman** [JarrodCTaylor/authenticated-compojure-api#3]
I get the following error when I try to run `lein ring server`
```
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (0) passed to: generate/generate-query-fn/query-wrapper-fn--18819, compiling:(/Users/maxim/tmp/authenticated-compojure-api/target/db1d7cdf39baa9ac90706dac95bbb0cae2cab641-init.clj:1:4)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (0) passed to: generate/generate-query-fn/query-wrapper-fn--18819
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:28)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at authenticated_compojure_api.handler$init.invoke(handler.clj:17)
	at clojure.lang.Var.invoke(Var.java:375)
	at ring.server.standalone$serve.doInvoke(standalone.clj:95)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at ring.server.leiningen$serve.invoke(leiningen.clj:21)
	at user$eval21183.invoke(db1d7cdf39baa9ac90706dac95bbb0cae2cab641-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 11 more
Subprocess failed
```

**Comment by JarrodCTaylor** [comment]
I tend to write very thorough READMEs however as you can tell that part of this project hasn't been fleshed out yet as I didn't think anyone other than myself was looking at it. I will try to get a proper set of instructions for running and testing the application locally up in the next few days. 

In the mean time the source of your error comes from not having a `profiles.clj` which provides the necessary environment variables the API requires. You will need to provide the database url, auth-key for signed tokens and credentials to send the reset emails (I use mandril) the file should look something like this:

``` clojure
{:dev-env-vars  {:env {:database-url  "postgres://auth_user:password1@127.0.0.1:5432/auth_local?stringtype=unspecified"
                       :user-email    "your.email@gmail.com"
                       :user-pass-key "mandril-key"
                       :auth-key      "random-key-for-signed-tokens"}}
 :test-env-vars {:env {:database-url  "postgres://auth_user:password1@127.0.0.1:5432/auth_test?stringtype=unspecified"
                       :auth-key      "random-key-for-signed-tokens"}}}
``` 

Adding that file should get you up and running. Assuming you have the database and user set up as needed.

**Comment by mveytsman** [comment]
Thanks!

I was just looking at this project as a way of figuring out how to use auth middleware with compjure-api. Looks like reading through your code helped, though what I really want is to say

```
 (GET* "/foo" []
          :return s/Any

          (ok {:types artifact/types})
```

**Comment by JarrodCTaylor** [comment]
Glad the project helped some.
