### ISSUE TITLE
Error running `lein run -m authenticated-compojure-api.server 3000` command

### ISSUE THREAD

**Issue by mattjmorrison** [JarrodCTaylor/authenticated-compojure-api#6]
Any ideas?

```
Retrieving com/draines/postal/1.11.4/postal-1.11.4.jar from clojars
Exception in thread "main" clojure.lang.ArityException: Wrong number of args (0) passed to: generate/generate-query-fn/query-wrapper-fn--1929, compiling:(/private/var/folders/p_/5d_p8gyx4vb365k58h53hm980000gn/T/form-init8644130707431558009.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7239)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (0) passed to: generate/generate-query-fn/query-wrapper-fn--1929
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.AFn.invoke(AFn.java:28)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at authenticated_compojure_api.server$create_tables.invoke(server.clj:7)
        at authenticated_compojure_api.server$_main.invoke(server.clj:13)
        at clojure.lang.Var.invoke(Var.java:379)
        at user$eval5.invoke(form-init8644130707431558009.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        ... 11 more
```

**Comment by JarrodCTaylor** [comment]
You need to create a `profiles.clj` in the root of the project to store the environment variables. It is blowing up looking for the database you want to connect to. The readme has an example of what the file should look like https://github.com/JarrodCTaylor/authenticated-compojure-api#add-profilesclj

Also make sure that the database and user (also in the readme) exist then you should be good to go.

**Comment by mattjmorrison** [comment]
It looks like I dropped my `profiles.clj` in the `src` directory instead of in the root directory for some reason. Moving it fixed it, thanks.
